name: Build and Deploy Container

on:
  push:
    branches:
      - '**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
   
    - name: Set environment from secrets
      run: |
        echo "REGISTRY_URL=${{ vars.REGISTRY_URL }}" >> $GITHUB_ENV
        echo "REGISTRY_USERNAME=${{ vars.REGISTRY_USERNAME }}" >> $GITHUB_ENV
        echo "REGISTRY_PASSWORD=${{ secrets.REGISTRY_PASSWORD }}" >> $GITHUB_ENV
        echo "IMAGE_NAME=${{ vars.IMAGE_NAME }}" >> $GITHUB_ENV

    - name: Install Podman
      run: |
        sudo apt-get update
        sudo apt-get -y install podman

    - name: Log in to container registry
      run: |
        echo "${REGISTRY_PASSWORD}" | podman login \
          --username "${REGISTRY_USERNAME}" \
          --password-stdin \
          "${REGISTRY_URL}"

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    - name: Install devcontainer
      run: npm install -g @devcontainers/cli

    - name: Build the devcontainer
      run: |
        devcontainer build \
          --docker-path "$(which podman)" \
          --workspace-folder . \
          --image-name "${IMAGE_NAME}" \
          --push true
        
    #- name: Push to container registry
    #  run: |
    #    podman push \
    #      "localhost/${IMAGE_NAME}:latest" \
    #      "${REGISTRY_URL}/${REGISTRY_USERNAME}/${IMAGE_NAME}:latest"
